[package]
name = "social-parser-rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
social_parser = { path = "../../crates/social-parser" }

[[example]]
name = "loadandsave"
path = "examples/loadandsave.rs"
