name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 1 * *' # At 00:00 on day-of-month 1 (once a month)

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/stale@v9.0.0
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'work-in-progress'
